---
- name: Deploy Flask app on Debian-based Droplet
  hosts: droplet
  become: yes
  gather_facts: yes
  vars:
    app_user: appuser

  tasks:
      - name: Create application user
      ansible.builtin.user:
        name: "{{ app_user }}"
        shell: /bin/bash
        state: present
        
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install necessary packages
      apt:
        pkg:
          - python3-pip
          - python3-dev
          - nginx
        state: present

    - name: Install Gunicorn and Flask
      pip:
        name:
          - gunicorn
          - Flask
        state: present
        executable: pip3

    - name: Clone Flask app repository
      git:
        repo: <your_repository>
        dest: /home/<your_ssh_user>/<your_repository_folder>

    - name: Install Flask app requirements
      pip:
        requirements: /home/<your_ssh_user>/<your_repository_folder>/requirements.txt
        state: present
        executable: pip3

    - name: Create Gunicorn systemd service file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Gunicorn instance to serve Flask app
          After=network.target

          [Service]
          User=<your_ssh_user>
          Group=www-data
          WorkingDirectory=/home/<your_ssh_user>/<your_repository_folder>
          Environment="PATH=/home/<your_ssh_user>/.local/bin"
          ExecStart=/home/<your_ssh_user>/.local/bin/gunicorn --workers 3 --bind unix:/home/<your_ssh_user>/<your_repository_folder>/gunicorn.sock <your_flask_app>:app

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/gunicorn.service

    - name: Start and enable Gunicorn service
      ansible.builtin.systemd:
        name: gunicorn
        state: started
        enabled: yes

    - name: Configure Nginx to proxy requests to Gunicorn
      ansible.builtin.copy:
        content: |
          server {
              listen 80;
              server_name <your_domain_or_IP>;

              location / {
                  include proxy_params;
                  proxy_pass http://unix:/home/<your_ssh_user>/<your_repository_folder>/gunicorn.sock;
              }
          }
        dest: /etc/nginx/sites-available/<your_flask_app>

    - name: Create a symbolic link to the Nginx configuration file
      ansible.builtin.file:
        src: /etc/nginx/sites-available/<your_flask_app>
        dest: /etc/nginx/sites-enabled/<your_flask_app>
        state: link

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test_result
      changed_when: False

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
      when: nginx_test_result.stdout.find('successful') != -1

    - name: Allow HTTP traffic
      ansible.builtin.ufw:
        rule: allow
        name: Nginx Full
